apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: security-gate
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: security-gate
  namespaceSelector:
    matchNames:
      - migsec
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
