apiVersion: v1
kind: Secret
metadata:
  name: security-gate-secrets
  namespace: migsec
type: Opaque
stringData:
  API_TOKEN: "dev-token"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
