apiVersion: v1
kind: Service
metadata:
  name: security-gate
  namespace: migsec
  labels:
    app: security-gate
spec:
  selector:
    app: security-gate
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
